---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config-v2
  namespace: home
#  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #volumeName: pvc-nfs-zigb2mqtt-data      
#  storageClassName: ceph-block
