---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.39.0
    env:
      TZ: "America/Jamaica"
      ZIGBEE2MQTT_DATA: /data
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v2
        mountPath: "/data"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    # These config values are not what is my current state of zigbee2mqtt
    # It's merely a guide for the initial start up on a fresh install
    # Everything after the first start is managed in the UI
    config:
      homeassistant: false
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://${METALLB_MQTT_ADDR}:1883"
      serial:
        port: "tcp://172.16.255.80:6638"
        adapter: ezsp
      advanced:
        log_output:
          - console
        network_key: GENERATE
        pan_id: GENERATE
      frontend:
        port: 8880
