---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zb.fatheadl.duckdns.org`)
      services:
        - kind: Service
          name: zigbee2mqtt
          port: 8123
  tls:
    certResolver: le
