---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: homebridge
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true

  values:
    image:
      repository: ghcr.io/oznu/homebridge
      tag: 2202-02-08
      pullPolicy: IfNotPresent


    env:
      TZ: "America/Jamaica"
      PUID: "1001"
      PGID: "1001"
      HOMEBRIDGE_CONFIG_UI: 1
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    persistence:
      config:
      enabled: true
      mountPath: /homebridge
      existingClaim: homebridge-config-v1
