---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hb.fatheadl.duckdns.org`)
      services:
        - kind: Service
          name: homebridge
          port: 8581
  tls:
    certResolver: le
