---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1l2hdufupfc6a8yrsgvvqvylzvyjcztx9mhmultt8dg2gye27qansv558sy
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1l2hdufupfc6a8yrsgvvqvylzvyjcztx9mhmultt8dg2gye27qansv558sy
