---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs-truenas
  namespace: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.nfs"

    storageClasses:
    - name: freenas-nfs-csi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs

      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
        
      volumeSnapshotClasses:
        – name: freenas-nfs

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: truenas.home
          port: 80
          apiKey: 1-2BpfAxQppwVC52LI57WwEaHnPVme3UY3n2xAN2aGTLkIzmSvYRXGnb4itXMiH8Ep
          username: root
          #password: anythingatall
          allowInsecure: true
        sshConnection:
          host: truenas.home
          port: 22
          username: root
          # use either password or key
          password: "anythingatall"
            #      privateKey: |
            #        -----BEGIN RSA PRIVATE KEY-----
            #        ...
            #        -----END RSA PRIVATE KEY-----
        zfs:
          datasetParentName: data/k8s/nfs/vols
          detachedSnapshotsDatasetParentName: data/k8s/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: truenas.home
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""
