---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
  namespace: home
  labels:
    app.kubernetes.io/name: homeassistant  
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pvc-nfs-home-assistant-data      
  #storageClassName: longhorn
