---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
#  dependsOn:
#    - name: mosquitto
#      namespace: home
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.12.5
    env:
      TZ: "America/Jamaica"
#    envFrom:
#      - secretRef:
#          name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_HOMEASSISTANT_ADDR}"
        externalTrafficPolicy: Local
      #externalIPs:
      #- "${METALLB_HOMEASSISTANT_ADDR: 172.16.255.31}"
      #externalTrafficPolicy: Local
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
        mountPath: /config        
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
