---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: node-red
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ha.fatheadl.duckdns.org`)
      services:
        - kind: Service
          name: home-assistant
          port: 8123
  tls:
    certResolver: le
