---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-k8s-share-pv
  namespace: default
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-k8s-share-pvc
  storageClassName: nfs-client
  nfs:
    server: omv3.home
    path: "/fatheadl"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-k8s-share-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi
