kind: Secret
ansible_user: ENC[AES256_GCM,data:lSZi+Tz0by8=,iv:bg7C7gy3gJj4su4fIp/WRXfNrN57AoEtGHCCYnXDGJs=,tag:P7jZ5WXayZfmILuP3tmo2w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AaldnxXj9fwh29k=,iv:iHJfUb4/FDdQETvaCSIwnagx89E7KoldYWwMXkgnly4=,tag:JJtlElWu9JUmbqx1SFUP3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2hdufupfc6a8yrsgvvqvylzvyjcztx9mhmultt8dg2gye27qansv558sy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdTF6MHNjYWtIQzZLeVVY
            Q3JKL3NUYUF3azVGYnI0eGUyOUovS2VRR3pVCjRkWnNGSkpBOXZNaFVqYytBWXlT
            MmxicGxJYUFjakNpc1QxREozK0hzeTgKLS0tIHZtMXpIOHo2Rmd6SjhCWlFqSXdO
            eXNsMi8vT2RKVElFTGJkRUVzU1U5VnMKiQK+TOsK8Ri9xeHt2dZeWdLe+c2ptgsD
            7iQwkO4h2EccgDmKbLW2WbocwZOA6cMTpvYus5fY6iJWfEaorO5JdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-11T15:33:08Z"
    mac: ENC[AES256_GCM,data:zBEpp5vq5Shq1irDDBHf6p6oLnjhQS6jbtLwp3QdMFrN08v/RdSK/oOgRPpAt3gd4f/S/eu8DX1wAvTf9nHFu7qw4m8VJt05GeWrNGaCM6rRKkKIO5BJYWmEFRkPYrvxORSC9mM/wk5pUNwoDbmkCsHUtxeDYbXL9pd4ai+TTLg=,iv:Y++Qk5ImZ+9mRfmYhJ3Tv14Cl92otpmJI0qAwzl9r7A=,tag:7X6n8XrU1OgHBs5Il1dTbA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
