---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.16.255.30-172.16.255.39
  METALLB_TRAEFIK_ADDR: 172.16.255.30
  METALLB_HOMEASSISTANT_ADDR: 172.16.255.31
  METALLB_MQTT_ADDR: 172.16.255.32
