# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:iOjHPbfoZfmYaT/9IyS8vJDpAvjSZZ6JrcmR6zgebkJKzRYs,iv:L5sOiA+l7xfR36qc39np6unYoSLiGsdiiZNoTMp3SFQ=,tag:xh8uMjy0kmFDBcOX/gCUiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2hdufupfc6a8yrsgvvqvylzvyjcztx9mhmultt8dg2gye27qansv558sy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VGRBZG4vZmxzY05pa3dw
            ZjJJcm1zQmNBTEc1dFZoMlFkeWVKVE5XV1hNCmFrQVhZcERVSVd3akN2bXgrVzRm
            VTZaZm13VU5sZ3JFY2dHWUNJSGpzUjgKLS0tIEwzR1dLRTFqbHhzL2RGVWd4bGZ6
            TCtFU0o3SVVtcXZIdVBpb29SY3BwdkkKD8Gw8LbBwX9AUH84xF6lojn4KF9rU8g2
            Dij5cV1evtE1pYlELc1F+xKVab2WWAvbW3u6AKm/T28q8VGCh91gBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-11T15:19:23Z"
    mac: ENC[AES256_GCM,data:A+d1DyfHdVIvJNcUNQDQ+GrNJi9hAqbIU4L3VbofT/8IgYrcSu+a9bgGuxh/71sOKNHumqcTLdkrrTYJUqJpLJq4sY5DoPPUW3nAku5Bps6S1a9wHY9S5YLxGGdAplm8tQz5HBTOczf7eZxgZG9+ROgMuM8daM/ibMbdLVJwPJ8=,iv:aXqdIs9n+JQDVcnS3DUHG+R3OJ9fWPl/g0/45WAfyGI=,tag:SbcTcACppMu8WRtSTKIddg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
