# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:j99SQqwt4XZGIvH0RNUp2Mp50Dgh4CZ+g7GoDI6p7cn6PkJE,iv:hm5p6dJsy1dY0lDCXsJ92cL4ZSEg8mDnPDI5G8x9n5U=,tag:yMPev9CAmKhsgyQhms+aUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2hdufupfc6a8yrsgvvqvylzvyjcztx9mhmultt8dg2gye27qansv558sy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRmtnbnVWNUhMNFdqSnZM
            OTNRY05ZNTQxTThkcEpHTzR1Z0l2b1pTbGc4CnNWaFJENDI3YUNtaWQ3d3dLSGtD
            SnJTbHFVbjR0dUN5d2dpVjF1TW5oTGsKLS0tIG9maXcxQnJ1WHkvTE81UnFpN1Uw
            TlZVajhrcTA2NmgwYmlRUDJOeW5GSEUKotaDl3IIqJOO8gIX61R/Nss3PueLmLZI
            yuUU02mxdZHPCGeYQ5eEeb53MfUuUqy9AbVo+X8guI8Z+oD7CG6XHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-11T15:33:08Z"
    mac: ENC[AES256_GCM,data:+aRlrfcKEflXg1nDsvo6SefS6e/6mwZKH4nJXlWNQUFe5ESHYfLq93aD8mDwLV4F+lvzrmUlZcbIfYSw56oc/tJOlZNGYpn7SdrmrH9aiw/sTJyzBiU7YVxdWEMIO9394MC27RWjF72MDbiL0ILOd4D+pkiOK+x9te3+FT2vOhA=,iv:ko32DKfBcGPxBQBwKN7mK9t58DXEuN5pww0PoSj8Ojs=,tag:8wH0wsnvxoE8sI8N7BplrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
