---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-config-v1
  namespace: home
  labels:
    app.kubernetes.io/name: mosquitto  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: mqtt-config-v1   
  #storageClassName: longhorn
