---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.15
    env:
      TZ: "America/Jamaica"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_MQTT_ADDR}"
        externalTrafficPolicy: Local
        
    configmap:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous true
            persistence true
            persistence_location /mosquitto/data
            connection_messages false
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        volumeSpec:
          configMap:
            name: mosquitto-config
      data:
        enabled: true
        existingClaim: mqtt-config-v1
        mountPath: /mosquitto/data
        
          

#    auth:
#      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mqtt

#      configinc:
#        enabled: true
#        type: custom
#        volumeSpec:
#          secret:
#            secretName: mosquitto
