---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  #dependsOn:
    #- name: home-assistant
      #namespace: home
  values:
    #initContainers:
      #workingDir: /data
      #volumeMounts:
        #- name: config
          #mountPath: /data
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v2.2.2
    env:
      TZ: "America/Jamaica"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"

    persistence:
      config:
        enabled: true
        existingClaim: node-red-config-v1
        mountPath: "/data"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
