---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
  
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: nfs-external-provisioner
  resources:
    requests:
      storage: 128Mi
