---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
  labels:
    app: hajimari
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 128Mi
