---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hajimari
  namespace: default  
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hajimari.fatheadl.duckdns.org`)
      services:
        - kind: Service
          name: hajimari
          port: 3000
  tls:
    certResolver: le
